name: theduck
version: stable
version-script: git -C parts/thefuck/build describe --abbrev=0 --tags
summary: Magnificent app which corrects your previous console command.
description: |
  The Fuck tries to match a rule for the previous command,
  creates a new command using the matched rule and runs it.

grade: stable
confinement: classic

apps:
  thefuck:
    command: bin/theduck
    environment:
        PYTHONIOENCODING: utf-8
  duck:
    command: bin/duck
    environment:
        PYTHONIOENCODING: utf-8

parts:
  theduck:
    source: https://github.com/avinashsvinu/theduck.git
    plugin: python
